# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Alternative(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, created_at: str=None, updated_at: str=None, comment: str=None, name: str=None, domain_name: str=None):  # noqa: E501
        """Alternative - a model defined in Swagger

        :param created_at: The created_at of this Alternative.  # noqa: E501
        :type created_at: str
        :param updated_at: The updated_at of this Alternative.  # noqa: E501
        :type updated_at: str
        :param comment: The comment of this Alternative.  # noqa: E501
        :type comment: str
        :param name: The name of this Alternative.  # noqa: E501
        :type name: str
        :param domain_name: The domain_name of this Alternative.  # noqa: E501
        :type domain_name: str
        """
        self.swagger_types = {
            'created_at': str,
            'updated_at': str,
            'comment': str,
            'name': str,
            'domain_name': str
        }

        self.attribute_map = {
            'created_at': 'created_at',
            'updated_at': 'updated_at',
            'comment': 'comment',
            'name': 'name',
            'domain_name': 'domain_name'
        }

        self._created_at = created_at
        self._updated_at = updated_at
        self._comment = comment
        self._name = name
        self._domain_name = domain_name

    @classmethod
    def from_dict(cls, dikt) -> 'Alternative':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The alternative of this Alternative.  # noqa: E501
        :rtype: Alternative
        """
        return util.deserialize_model(dikt, cls)

    @property
    def created_at(self) -> str:
        """Gets the created_at of this Alternative.


        :return: The created_at of this Alternative.
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: str):
        """Sets the created_at of this Alternative.


        :param created_at: The created_at of this Alternative.
        :type created_at: str
        """

        self._created_at = created_at

    @property
    def updated_at(self) -> str:
        """Gets the updated_at of this Alternative.


        :return: The updated_at of this Alternative.
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: str):
        """Sets the updated_at of this Alternative.


        :param updated_at: The updated_at of this Alternative.
        :type updated_at: str
        """

        self._updated_at = updated_at

    @property
    def comment(self) -> str:
        """Gets the comment of this Alternative.


        :return: The comment of this Alternative.
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment: str):
        """Sets the comment of this Alternative.


        :param comment: The comment of this Alternative.
        :type comment: str
        """

        self._comment = comment

    @property
    def name(self) -> str:
        """Gets the name of this Alternative.


        :return: The name of this Alternative.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Alternative.


        :param name: The name of this Alternative.
        :type name: str
        """

        self._name = name

    @property
    def domain_name(self) -> str:
        """Gets the domain_name of this Alternative.


        :return: The domain_name of this Alternative.
        :rtype: str
        """
        return self._domain_name

    @domain_name.setter
    def domain_name(self, domain_name: str):
        """Sets the domain_name of this Alternative.


        :param domain_name: The domain_name of this Alternative.
        :type domain_name: str
        """

        self._domain_name = domain_name
