# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Domain(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, created_at: str=None, updated_at: str=None, comment: str=None):  # noqa: E501
        """Domain - a model defined in Swagger

        :param created_at: The created_at of this Domain.  # noqa: E501
        :type created_at: str
        :param updated_at: The updated_at of this Domain.  # noqa: E501
        :type updated_at: str
        :param comment: The comment of this Domain.  # noqa: E501
        :type comment: str
        """
        self.swagger_types = {
            'created_at': str,
            'updated_at': str,
            'comment': str
        }

        self.attribute_map = {
            'created_at': 'created_at',
            'updated_at': 'updated_at',
            'comment': 'comment'
        }

        self._created_at = created_at
        self._updated_at = updated_at
        self._comment = comment

    @classmethod
    def from_dict(cls, dikt) -> 'Domain':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The domain of this Domain.  # noqa: E501
        :rtype: Domain
        """
        return util.deserialize_model(dikt, cls)

    @property
    def created_at(self) -> str:
        """Gets the created_at of this Domain.


        :return: The created_at of this Domain.
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: str):
        """Sets the created_at of this Domain.


        :param created_at: The created_at of this Domain.
        :type created_at: str
        """

        self._created_at = created_at

    @property
    def updated_at(self) -> str:
        """Gets the updated_at of this Domain.


        :return: The updated_at of this Domain.
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: str):
        """Sets the updated_at of this Domain.


        :param updated_at: The updated_at of this Domain.
        :type updated_at: str
        """

        self._updated_at = updated_at

    @property
    def comment(self) -> str:
        """Gets the comment of this Domain.


        :return: The comment of this Domain.
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment: str):
        """Sets the comment of this Domain.


        :param comment: The comment of this Domain.
        :type comment: str
        """

        self._comment = comment
