# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Relay(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, created_at: str=None, updated_at: str=None, comment: str=None, name: str=None, smtp: str=None):  # noqa: E501
        """Relay - a model defined in Swagger

        :param created_at: The created_at of this Relay.  # noqa: E501
        :type created_at: str
        :param updated_at: The updated_at of this Relay.  # noqa: E501
        :type updated_at: str
        :param comment: The comment of this Relay.  # noqa: E501
        :type comment: str
        :param name: The name of this Relay.  # noqa: E501
        :type name: str
        :param smtp: The smtp of this Relay.  # noqa: E501
        :type smtp: str
        """
        self.swagger_types = {
            'created_at': str,
            'updated_at': str,
            'comment': str,
            'name': str,
            'smtp': str
        }

        self.attribute_map = {
            'created_at': 'created_at',
            'updated_at': 'updated_at',
            'comment': 'comment',
            'name': 'name',
            'smtp': 'smtp'
        }

        self._created_at = created_at
        self._updated_at = updated_at
        self._comment = comment
        self._name = name
        self._smtp = smtp

    @classmethod
    def from_dict(cls, dikt) -> 'Relay':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The relay of this Relay.  # noqa: E501
        :rtype: Relay
        """
        return util.deserialize_model(dikt, cls)

    @property
    def created_at(self) -> str:
        """Gets the created_at of this Relay.


        :return: The created_at of this Relay.
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: str):
        """Sets the created_at of this Relay.


        :param created_at: The created_at of this Relay.
        :type created_at: str
        """

        self._created_at = created_at

    @property
    def updated_at(self) -> str:
        """Gets the updated_at of this Relay.


        :return: The updated_at of this Relay.
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: str):
        """Sets the updated_at of this Relay.


        :param updated_at: The updated_at of this Relay.
        :type updated_at: str
        """

        self._updated_at = updated_at

    @property
    def comment(self) -> str:
        """Gets the comment of this Relay.


        :return: The comment of this Relay.
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment: str):
        """Sets the comment of this Relay.


        :param comment: The comment of this Relay.
        :type comment: str
        """

        self._comment = comment

    @property
    def name(self) -> str:
        """Gets the name of this Relay.


        :return: The name of this Relay.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Relay.


        :param name: The name of this Relay.
        :type name: str
        """

        self._name = name

    @property
    def smtp(self) -> str:
        """Gets the smtp of this Relay.


        :return: The smtp of this Relay.
        :rtype: str
        """
        return self._smtp

    @smtp.setter
    def smtp(self, smtp: str):
        """Sets the smtp of this Relay.


        :param smtp: The smtp of this Relay.
        :type smtp: str
        """

        self._smtp = smtp
